ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "dockerImage" TEXT;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "envVars" JSONB;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "workerCommand" TEXT;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "withPostgres" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "withRedis" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "port" INTEGER NOT NULL DEFAULT 3000;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "healthPath" TEXT NOT NULL DEFAULT '/health';
