'use client'

import { useState } from 'react'
import { generateOpsInsight } from '../app/actions'
import { Sparkles, AlertCircle, Loader2 } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

export default function OpsInsightPanel() {
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)

  const handleGenerate = async () => {
    setLoading(true)
    setError(null)
    setResult(null)
    
    try {
      const res = await generateOpsInsight()
      if (res.error) {
        setError(res.error)
      } else {
        setResult(res.data)
      }
    } catch (e: any) {
      setError(e.message || 'An error occurred')
    } finally {
      setLoading(false)
    }
  }

  // Pre-process the insight string:
  // 1. Replace literal <br> or <br/> with standard markdown newlines
  // 2. Remove weird loose bullet points generated by some models (like '•') 
  //    if they appear alone on a line or just before markdown headers
  const getCleanMarkdown = (text: string) => {
    return text
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/^[•·]\s*$/gm, '') 
      .replace(/^[•·]\s*(?=\*)/gm, '')
      .replace(/^[•·]\s*(?=-)/gm, '')
  }

  return (
    <div className="mt-8 p-6 rounded-2xl bg-card border border-border/50 shadow-sm relative overflow-hidden">
      <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/5 rounded-full blur-3xl -mr-10 -mt-10" />
      
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-2">
        <div className="flex items-center gap-3 text-foreground z-10">
          <div className="w-10 h-10 rounded-xl bg-purple-500/10 flex items-center justify-center text-purple-500 border border-purple-500/20 shadow-sm">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-semibold text-foreground">AI Ops Insight</h3>
            <p className="text-xs text-muted-foreground">Synthesize your deployment state using an LLM</p>
          </div>
        </div>
        
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="px-5 py-2.5 rounded-xl font-medium text-sm transition-all duration-200 active:scale-95 shadow-sm bg-purple-600 text-white hover:bg-purple-700 border border-purple-800 disabled:opacity-50 z-10 flex items-center gap-2"
        >
          {loading ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" /> Generating...
            </>
          ) : (
            'Generate Insight'
          )}
        </button>
      </div>

      {error && (
        <div className="mt-6 p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 flex items-start gap-3 relative z-10">
          <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
          <p className="text-sm font-medium">{error}</p>
        </div>
      )}

      {result && (
        <div className="mt-6 space-y-4 relative z-10 animate-in fade-in slide-in-from-bottom-2 duration-300">
          <div className="p-6 rounded-xl bg-background/50 backdrop-blur-sm border border-border/50">
            <article className="prose prose-sm dark:prose-invert max-w-none 
              prose-headings:text-purple-400 prose-headings:font-semibold 
              prose-a:text-purple-400 hover:prose-a:text-purple-300 
              prose-strong:text-foreground prose-strong:font-semibold
              prose-table:border-collapse prose-th:bg-muted/50 prose-th:p-3 prose-td:p-3
              prose-td:border-t prose-td:border-border/50 prose-th:border-b prose-th:border-border/50
              prose-code:text-purple-300 prose-code:bg-purple-500/10 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded-md prose-code:before:content-none prose-code:after:content-none
              prose-ul:list-disc prose-ul:pl-4
              prose-ol:list-decimal prose-ol:pl-4">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {getCleanMarkdown(result.insight)}
              </ReactMarkdown>
            </article>
          </div>
          
          <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground pt-2">
            <div className="flex items-center gap-2 bg-muted/50 px-3 py-1.5 rounded-md border border-border/50">
              <span className="font-medium">Model:</span>
              <span className="text-foreground">{result.model}</span>
            </div>
            <div className="flex items-center gap-2 bg-muted/50 px-3 py-1.5 rounded-md border border-border/50">
              <span className="font-medium">Cost:</span>
              <span className="text-emerald-500 font-medium">${result.costUsd?.toFixed(6)}</span>
            </div>
            <div className="flex items-center gap-2 bg-muted/50 px-3 py-1.5 rounded-md border border-border/50">
              <span className="font-medium">Context:</span>
              <span className="text-foreground">{result.sources?.applicationCount} apps, {result.sources?.eventCount} events</span>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
